CREATE TABLE IF NOT EXISTS consumers(
   id serial PRIMARY KEY,
   name VARCHAR (50) UNIQUE NOT NULL,
   taxId VARCHAR (50) UNIQUE NOT NULL,
   addr VARCHAR (300) NOT NULL,
   tel VARCHAR (300) UNIQUE NOT NULL,
   contact VARCHAR (50) NOT NULL,
   create_at TIMESTAMPTZ NOT NULL
);